---
title: "tidycoral_practice"
author: "Leslie Roberson"
date: "6/19/2019"
output: html_document
---

```{r setup, warning = FLASE, message = FALSE}
library(tidyverse)
library(janitor) # install.packages("janitor")
library(skimr) # install.packages("skimr")
library(stringr) # install.packages("stringr)
```

## more shortcuts

Highlight between words = option + shift
Highlight sections and hop left or right = option + shift + arrow
Hope to end but don't hightlight anything = cmd + arrow 
arrow = option + minus
cmd + option + i = new code chunk
```{r load data}
## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'
## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'
```

```{r benthic raw}
benthic_raw <- read_csv(benthic_url)
head(benthic_raw)
```
# Wrangle
One hash makes the header bold
```{r}
benthic <- benthic_raw %>%
  janitor::clean_names()  # keep track/specify where this function comes from or force r to use that package
# explore
head(benthic)

# select our columns
benthic <- benthic %>%
  select(id_name, point, x, y, id_date) %>%
  mutate(date = stringr::str_remove_all(id_date, "#"))

```
use skimr to explore data 
```{r}
skimr::skim(benthic) # I like this one

unique(benthic$id_name)

ggplot(data = benthic, 
       aes(date, fill = id_name)) +
  geom_bar()
```
#Buoy data!
```{r buoy data}
#import buoy data
buoy_raw <- readr::read_csv(buoy_url) # this doesn't work bc it's not a csv

buoy_raw <- readr::read_table2(buoy_url) 
head(buoy_raw) 
```
# Wrangle 
```{r}
buoy <- buoy_raw
names(buoy)

# overwrite current column names
names(buoy) <- str_c( # joins multiple strings into a single string
  names(buoy),
  buoy %>% filter(`#YY`== "#yr"), # find the row where column #YY = #yr
  sep = "_")

# clean up hashes and slashes 
names(buoy) <- str_replace_all(names(buoy), "#", "") # replace # with nothing
names(buoy) <- str_replace_all(names(buoy), "/", "")

#remove redundant row
buoy <- buoy %>%
  filter(`YY_yr` != "#yr") # keep anything that isn't that first row
```
#Explore!
```{r}
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar() # still really messy lots of things to do
```
# join!
```{r}
head(benthic)
head(buoy)

# unite buoy dates so they look the same as the benthic dates
buoy <- buoy %>% 
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-") # make new col called date by uniting the year month day cols in that order
bb_join <- benthic %>% 
  left_join(buoy, by = "date") # something's wrong, it's too huge
# figure out why
# ok lots of repeated rows 
rm(bb_join)
```




